# Generated by Django 4.2 on 2024-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='duration',
            field=models.SmallIntegerField(verbose_name='Продолжительность в минутах'),
        ),
    ]
